server:
  port: 8080

spring:
  # 1. Cấu hình Database
  datasource:
    url: jdbc:mysql://localhost:3306/shop_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: nam2502
    driver-class-name: com.mysql.cj.jdbc.Driver

  # 2. Cấu hình Hibernate/JPA
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  # 3. Cấu hình Thymeleaf (Tắt cache để sửa HTML là thấy thay đổi ngay)
  thymeleaf:
    cache: false

# 4. Biến upload path (Sửa lỗi Placeholder)
upload:
  path: uploads

# 5. Bật Log Debug Security (Để kiểm tra luồng Role/Login)
logging:
  level:
    org.springframework.security: DEBUG

# 6. Cấu hình Swagger
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  show-actuator: true
  scanner: # Cho phép Swagger hiển thị cả @Controller
    controller:
      enabled: true
    openapi:
      info:
        title: "HỆ THỐNG QUẢN LÝ SHOP 2026"
        description: "Dự án cá nhân - Quản lý kho hàng và bán hàng"
        version: "1.0.0"